server:
  port: 80
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: travel-plan
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://47.102.122.186:3306/travel_plan?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/mapper/*/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
